apiVersion: apps/v1
kind: Deployment
metadata:
  name: feats-backend-user-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feats-backend-user-auth
  template:
    metadata:
      labels:
        app: feats-backend-user-auth
    spec:
      containers:
        - name: feats-backend-user-auth
          image: registry.digitalocean.com/group3/feats-backend:latest
          ports:
          - containerPort: 8089
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          envFrom:
          - configMapRef:
              name: feats-backend-config
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8prod,authenticate,user
          - name: POSTGRES_K8_PROD_USER
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_K8_PROD_USER
          - name: POSTGRES_K8_PROD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_K8_PROD_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_DB
          - name: POSTGRES_K8_PROD_PORT
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_K8_PROD_PORT
          - name: POSTGRES_K8_PROD_IP
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_K8_PROD_IP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: feats-backend-ingredient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feats-backend-ingredient
  template:
    metadata:
      labels:
        app: feats-backend-ingredient
    spec:
      containers:
        - name: feats-backend-ingredient
          image: registry.digitalocean.com/group3/feats-backend:latest
          ports:
          - containerPort: 8090
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          envFrom:
          - configMapRef:
              name: feats-backend-config
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8prod,ingredient
          - name: POSTGRES_K8_PROD_USER
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_K8_PROD_USER
          - name: POSTGRES_K8_PROD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_K8_PROD_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_DB
          - name: POSTGRES_K8_PROD_PORT
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_K8_PROD_PORT
          - name: POSTGRES_K8_PROD_IP
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_K8_PROD_IP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: feats-backend-recipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feats-backend-recipe
  template:
    metadata:
      labels:
        app: feats-backend-recipe
    spec:
      containers:
        - name: feats-backend-recipe
          image: registry.digitalocean.com/group3/feats-backend:latest
          ports:
          - containerPort: 8091
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          envFrom:
          - configMapRef:
              name: feats-backend-config
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8prod,recipe
          - name: POSTGRES_K8_PROD_USER
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_K8_PROD_USER
          - name: POSTGRES_K8_PROD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_K8_PROD_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_DB
          - name: POSTGRES_K8_PROD_PORT
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_K8_PROD_PORT
          - name: POSTGRES_K8_PROD_IP
            valueFrom:
              secretKeyRef:
                name: feats-backend-secret
                key: POSTGRES_K8_PROD_IP
---

apiVersion: v1
kind: Service
metadata:
  name: feats-backend-user-auth
spec:
  selector:
    app: feats-backend-user-auth
  ports:
    - protocol: TCP
      port: 8089 # external port to be exposed
      targetPort: 8089
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: feats-backend-ingredient
spec:
  selector:
    app: feats-backend-ingredient
  ports:
    - protocol: TCP
      port: 8090 # external port to be exposed
      targetPort: 8089
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: feats-backend-recipe
spec:
  selector:
    app: feats-backend-recipe
  ports:
    - protocol: TCP
      port: 8091 # external port to be exposed
      targetPort: 8089
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: feats-backend-ingredient
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feats-backend-ingredient
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: feats-backend-recipe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feats-backend-recipe
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: feats-backend-user-auth
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feats-backend-user-auth
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: feats-backend-config
data:
  service.url.authenticate.port: "8089"
  service.url.user.port: "8089"
  service.url.ingredient.port: "8090"
  service.url.recipe.port: "8091"
  service.url.authenticate.address: "feats-backend-user-auth"
  service.url.user.address: "feats-backend-user-auth"
  service.url.ingredient.address: "feats-backend-ingredient"
  service.url.recipe.address: "feats-backend-recipe"