apiVersion: apps/v1
kind: Deployment
metadata:
  name: feats-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feats-frontend
  template:
    metadata:
      labels:
        app: feats-frontend
    spec:
      containers:
      - name: feats-frontend
        image: registry.digitalocean.com/group3/feats-frontend:1.0.2
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: feats-frontend-config

---
apiVersion: v1
kind: Service
metadata:
  name: feats-frontend
spec:
  type: LoadBalancer
  selector:
    app: feats-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 80
      name: https

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: feats-frontend-config
data:
  VITE_PORT: "3000"
  VITE_HOST: "127.0.0.1"
  VITE_BACKEND_AUTHENTICATE_PORT: "8089"
  VITE_BACKEND_USER_PORT: "8089"
  VITE_BACKEND_INGREDIENT_PORT: "8090"
  VITE_BACKEND_RECIPE_PORT: "8091"
  VITE_BACKEND_REVIEW_PORT: "8091"
  VITE_BACKEND_NOTIFICATION_PORT: "8089"
  VITE_BACKEND_AUTHENTICATE_URL: "http://feats-backend"
  VITE_BACKEND_USER_URL: "http://feats-backend"
  VITE_BACKEND_INGREDIENT_URL: "http://feats-backend"
  VITE_BACKEND_RECIPE_URL: "http://feats-backend"
  VITE_BACKEND_REVIEW_URL: "http://feats-backend"
  VITE_BACKEND_NOTIFICATION_URL: "http://feats-backend"